version: '2'

services:
  mongodb:
    image: 'bitnami/mongodb:4.1'
    labels:
      kompose.service.type: nodeport
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami'
    environment:
      - MONGODB_ROOT_PASSWORD=admin
      - MONGODB_USERNAME=root
      - MONGODB_DATABASE=my_database

volumes:
  mongodb_data:
    driver: local
